### ISSUE TITLE
Confusing build instructions for Linux

### ISSUE THREAD

**Issue by Identity9165** [makigumo/MIPSCPU#6]
> Linux
> 
> Run install.sh from the Hopper-SDK. Then adjust your PATH to include the created gnustep-Linux-x86_64/bin/ path. Follow above instructions for building with cmake.

It's unclear that Hopper-SDK refers to your fork of the Hopper SDK, not the original HopperSDK.

Also for this reason gnustep-Linux-x86_64/bin/ path gets confusing, too. It needs to be recompiled from your fork.

IDK, maybe it's me but I found this confusing, maybe you can consider rephrasing it. Thanks for the plugin!

**Comment by makigumo** [comment]
Thanks for the pointer.

I tried to improve the description of the build process. If you still feel there might be room for improvement don't hesitate to comment.

**Comment by Identity9165** [comment]
Thank you! While recompiling gnustep with your patches I had to clone all of the makigumo/HopperSDK-v4 manually because "git clone --recursive" only downloads the "include/Hopper" but install.sh and patches are located outside of that directory.

That's how I build the plugin 😄 Maybe I was wrong but if you think this would improve the documentation, please consider adding cloning instructions too 👍

**Comment by makigumo** [comment]
I see, thanks for the clarification.

The SDK for Linux should be compiled apart from this plugin, as it is meant to be reused for other Hopper plugins as well. Also the included patches don't really change, compared to the SDK content. So you should use the original SDK archive from hopperapp.com for this step.
While you can achieve the same using my HopperSDK repo, I would like to discourage its use at this point.

My Hopper-SDK repository was only created to not let the other stuff inside the SDK clutter the sources (in branch `include`) and to keep track of changes in the SDK between versions.
