### ISSUE TITLE
I can’t use this plug-in to complete mips disassembly

### ISSUE THREAD

**Issue by h1zzz** [makigumo/MIPSCPU#7]
Hello there! I can’t use this plug-in to complete mips disassembly, but the plug-in can read the symbol table. My hopper version is 4.5.29 and macos catalina 10.15.7. I don’t know what went wrong, I hope I can get your help. Thank you.

**Comment by makigumo** [comment]
Works for me. Please describe your issue in more detail.

**Comment by h1zzz** [comment]
> 为我工作。请更详细地描述您的问题。

Hello, I am using hopper disassembler 4.5.29, after installing the MIPSCPU plug-in, I cannot disassemble the mips architecture program.
